# DEVELOPING THE SUDOKU GENERATOR

## PREPARING THE DEVELOPMENT ENVIRONMENT

Including path to previous directory in built-in variable `sys.path`, allowing access to the `sudoku` package:

In [1]:
import sys

sys.path.append('../')

Importing the libraries and the formulation of the problem:

In [2]:
import numpy as np
from sudoku.solvers import solver_exhaustive
from sudoku.utils import N, STEP, flatten_position, \
                         available_nums, objective_grid

pygame 2.5.2 (SDL 2.28.3, Python 3.11.4)
Hello from the pygame community. https://www.pygame.org/contribute.html


## GENERATOR

Fills the grid through the search strategy with backtracking and clears positions checking if the sudoku remains with a unique solution:

In [3]:
def sudoku_generator(clues=41):
    grid = np.zeros((N, N), dtype='int8')
    acts = [0 for _ in range(N**2)]

    s = 0
    while not objective_grid(grid):
        x, y = flatten_position(s)
        nums = available_nums(grid, x, y)

        if nums:
            rmve = np.random.randint(len(nums))
            num  = nums.pop(rmve)

            acts[s] = nums
        else:
            s -= 1

            while not acts[s]:
                x, y = flatten_position(s)
                grid[y, x] = 0
                s -= 1

            x, y = flatten_position(s)
            rmve = np.random.randint(len(acts[s]))
            num  = acts[s].pop(rmve)

        grid[y, x] = num
        s += 1

    positions = [(y, x)
                 for y in range(N)
                 for x in range(N)]

    while np.count_nonzero(grid) > clues:
        idx = np.random.randint(len(positions))
        pos = positions.pop(idx)        

        v = grid[pos]

        grid[pos] = 0
        if not np.all(solver_exhaustive(grid)):
            positions.append(pos)
            grid[pos] = v

    return grid

Testing the sudoku generator:

In [4]:
sudoku = sudoku_generator()

print(f'Instance created with {np.count_nonzero(sudoku)} clues =')
print(sudoku)

print()

print('Instance resolved =')
print(solver_exhaustive(sudoku))

Instance created with 41 clues =
[[6 4 7 0 5 3 8 0 0]
 [0 0 8 1 4 9 6 0 7]
 [9 0 0 0 0 0 4 3 2]
 [0 0 0 0 7 0 0 8 6]
 [0 6 0 9 1 8 7 0 0]
 [0 0 0 0 3 0 5 0 1]
 [7 8 0 0 6 0 0 4 0]
 [0 3 0 0 9 5 0 0 8]
 [0 5 0 8 2 0 9 7 3]]

Instance resolved =
[[6 4 7 2 5 3 8 1 9]
 [3 2 8 1 4 9 6 5 7]
 [9 1 5 6 8 7 4 3 2]
 [4 9 1 5 7 2 3 8 6]
 [5 6 3 9 1 8 7 2 4]
 [8 7 2 4 3 6 5 9 1]
 [7 8 9 3 6 1 2 4 5]
 [2 3 4 7 9 5 1 6 8]
 [1 5 6 8 2 4 9 7 3]]


In [5]:
sudoku = sudoku_generator()

print(f'Instance created with {np.count_nonzero(sudoku)} clues =')
print(sudoku)

print()

print('Instance resolved =')
print(solver_exhaustive(sudoku))

Instance created with 41 clues =
[[0 9 0 6 4 0 0 0 1]
 [1 2 0 0 0 0 0 9 0]
 [0 5 0 0 8 1 0 2 3]
 [0 7 1 4 0 0 9 3 8]
 [3 0 5 0 9 0 0 0 7]
 [0 0 0 0 3 0 0 6 0]
 [0 1 7 0 2 0 3 0 6]
 [5 0 2 7 6 0 1 0 9]
 [8 0 6 0 1 9 5 0 2]]

Instance resolved =
[[7 9 3 6 4 2 8 5 1]
 [1 2 8 5 7 3 6 9 4]
 [6 5 4 9 8 1 7 2 3]
 [2 7 1 4 5 6 9 3 8]
 [3 6 5 2 9 8 4 1 7]
 [4 8 9 1 3 7 2 6 5]
 [9 1 7 8 2 5 3 4 6]
 [5 3 2 7 6 4 1 8 9]
 [8 4 6 3 1 9 5 7 2]]


In [6]:
sudoku = sudoku_generator()

print(f'Instance created with {np.count_nonzero(sudoku)} clues =')
print(sudoku)

print()

print('Instance resolved =')
print(solver_exhaustive(sudoku))

Instance created with 41 clues =
[[9 0 5 0 0 8 0 7 0]
 [7 3 8 9 2 0 1 0 5]
 [0 0 4 0 5 0 8 2 9]
 [0 0 9 6 3 0 0 8 0]
 [0 0 0 5 7 4 0 0 1]
 [0 1 0 2 0 0 0 3 7]
 [2 0 3 8 0 0 7 1 0]
 [0 0 0 4 6 7 0 0 0]
 [0 0 0 3 1 2 4 5 0]]

Instance resolved =
[[9 2 5 1 4 8 6 7 3]
 [7 3 8 9 2 6 1 4 5]
 [1 6 4 7 5 3 8 2 9]
 [5 7 9 6 3 1 2 8 4]
 [3 8 2 5 7 4 9 6 1]
 [4 1 6 2 8 9 5 3 7]
 [2 4 3 8 9 5 7 1 6]
 [8 5 1 4 6 7 3 9 2]
 [6 9 7 3 1 2 4 5 8]]
