# SOLVING SUDOKU WITH BRUTE FORCE

## PREPARING THE DEVELOPMENT ENVIRONMENT

Including path to previous directory in built-in variable `sys.path`, allowing access to the `sudoku` package:

In [1]:
import sys

sys.path.append('../')

Importing the libraries and the formulation of the problem:

In [2]:
import numpy as np
from sudoku.utils import objective_grid, \
                         first_available_pos, \
                         available_nums

pygame 2.5.2 (SDL 2.28.3, Python 3.11.4)
Hello from the pygame community. https://www.pygame.org/contribute.html


## BACKTRACKING SEARCH

This search strategy employs a trial-and-error approach, manifesting as a brute force strategy. Upon encountering a configuration where the instance remains unresolved and there are no further valid movement options, the search backtracks until discovering a valid path without revisiting previously explored paths.

Obs.: It will serve to verify if a game instance possesses a unique solution, subsequently integrating with the valid game instance generator.




In [3]:
def backtracking(sudoku_grid):
    grid = sudoku_grid.copy()
    step = np.count_nonzero(grid == 0)

    moves = [None] * step
    actns = [None] * step

    size = 0
    while not objective_grid(grid):
        move = first_available_pos(grid)
        nums = available_nums(grid, move[1], move[0])

        if nums:
            grid[move] = nums.pop()
            moves[size] = move
            actns[size] = nums
            size += 1
        else:
            size -= 1
            
            while not actns[size]:   
                # The instance has no solution
                if size == 0:
                    return None

                # Undoing each modification to generate the next successor
                grid[moves[size]] = 0
                size -= 1

            move = moves[size]
            num  = actns[size].pop()

            grid[move] = num
            size += 1

    return grid

Testing the solver:

In [4]:
%%timeit

array = np.array([[5, 3, 0, 0, 7, 0, 0, 0, 0],
                  [6, 0, 0, 1, 9, 5, 0, 0, 0],
                  [0, 9, 8, 0, 0, 0, 0, 6, 0],
                  [8, 0, 0, 0, 6, 0, 0, 0, 3],
                  [4, 0, 0, 8, 0, 3, 0, 0, 1],
                  [7, 0, 0, 0, 2, 0, 0, 0, 6],
                  [0, 6, 0, 0, 0, 0, 2, 8, 0],
                  [0, 0, 0, 4, 1, 9, 0, 0, 5],
                  [0, 0, 0, 0, 8, 0, 0, 7, 9]])

_ = backtracking(array)

40.8 ms ± 4.11 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [5]:
array = np.array([[5, 3, 0, 0, 7, 0, 0, 0, 0],
                  [6, 0, 0, 1, 9, 5, 0, 0, 0],
                  [0, 9, 8, 0, 0, 0, 0, 6, 0],
                  [8, 0, 0, 0, 6, 0, 0, 0, 3],
                  [4, 0, 0, 8, 0, 3, 0, 0, 1],
                  [7, 0, 0, 0, 2, 0, 0, 0, 6],
                  [0, 6, 0, 0, 0, 0, 2, 8, 0],
                  [0, 0, 0, 4, 1, 9, 0, 0, 5],
                  [0, 0, 0, 0, 8, 0, 0, 7, 9]])

grid = backtracking(array)

print(f'Backtracking was sufficient to resolve the instance of the problem = {objective_grid(grid)}')

print()

print('Grid =')
print(grid)

Backtracking was sufficient to resolve the instance of the problem = True

Grid =
[[5 3 4 6 7 8 9 1 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 7 9 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 1 7 9]]


In [6]:
%%timeit

grid_inkala = np.array([[0, 0, 5, 3, 0, 0, 0, 0, 0],
                        [8, 0, 0, 0, 0, 0, 0, 2, 0],
                        [0, 7, 0, 0, 1, 0, 5, 0, 0],
                        [4, 0, 0, 0, 0, 5, 3, 0, 0],
                        [0, 1, 0, 0, 7, 0, 0, 0, 6],
                        [0, 0, 3, 2, 0, 0, 0, 8, 0],
                        [0, 6, 0, 5, 0, 0, 0, 0, 9],
                        [0, 0, 4, 0, 0, 0, 0, 3, 0],
                        [0, 0, 0, 0, 0, 9, 7, 0, 0]], dtype='int8')

_ = backtracking(grid_inkala)

18 s ± 546 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [7]:
grid_inkala = np.array([[0, 0, 5, 3, 0, 0, 0, 0, 0],
                        [8, 0, 0, 0, 0, 0, 0, 2, 0],
                        [0, 7, 0, 0, 1, 0, 5, 0, 0],
                        [4, 0, 0, 0, 0, 5, 3, 0, 0],
                        [0, 1, 0, 0, 7, 0, 0, 0, 6],
                        [0, 0, 3, 2, 0, 0, 0, 8, 0],
                        [0, 6, 0, 5, 0, 0, 0, 0, 9],
                        [0, 0, 4, 0, 0, 0, 0, 3, 0],
                        [0, 0, 0, 0, 0, 9, 7, 0, 0]], dtype='int8')

grid = backtracking(grid_inkala)

print(f'Backtracking was sufficient to resolve the instance of the problem = {objective_grid(grid)}')

print()

print('Grid =')
print(grid)

Backtracking was sufficient to resolve the instance of the problem = True

Grid =
[[1 4 5 3 2 7 6 9 8]
 [8 3 9 6 5 4 1 2 7]
 [6 7 2 9 1 8 5 4 3]
 [4 9 6 1 8 5 3 7 2]
 [2 1 8 4 7 3 9 5 6]
 [7 5 3 2 9 6 4 8 1]
 [3 6 7 5 4 2 8 1 9]
 [9 8 4 7 6 1 2 3 5]
 [5 2 1 8 3 9 7 6 4]]


## EXHAUSTIVE SEARCH

To verify the existence of more than one solution:

In [8]:
def exhaustive_search(sudoku_grid):
    grid = sudoku_grid.copy()
    step = np.count_nonzero(grid == 0)

    sol = None
    moves = [None] * step
    actns = [None] * step

    size = 0
    while True:
        if objective_grid(grid):
            # If no one has been found so far:
            #  -> Defines the solution
            # Otherwise, there is more than one solution:
            #  -> Return None
            if not np.all(sol):
                sol = grid.copy()
            else:
                return None

        move = first_available_pos(grid)
        if move:
            nums = available_nums(grid, move[1], move[0])

        if move and nums:
            grid[move] = nums.pop()
            moves[size] = move
            actns[size] = nums
            size += 1
        else:
            size -= 1
            
            while not actns[size]:   
                if size == 0:
                    return sol

                grid[moves[size]] = 0
                size -= 1

            move = moves[size]
            num  = actns[size].pop()

            grid[move] = num
            size += 1

Testing the algorithm with a single-solution instance:

In [9]:
single_solution = np.array([[5, 3, 0, 0, 7, 0, 0, 0, 0],
                            [6, 0, 0, 1, 9, 5, 0, 0, 0],
                            [0, 9, 8, 0, 0, 0, 0, 6, 0],
                            [8, 0, 0, 0, 6, 0, 0, 0, 3],
                            [4, 0, 0, 8, 0, 3, 0, 0, 1],
                            [7, 0, 0, 0, 2, 0, 0, 0, 6],
                            [0, 6, 0, 0, 0, 0, 2, 8, 0],
                            [0, 0, 0, 4, 1, 9, 0, 0, 5],
                            [0, 0, 0, 0, 8, 0, 0, 7, 9]])

grid = exhaustive_search(single_solution)
print(grid)

[[5 3 4 6 7 8 9 1 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 7 9 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 1 7 9]]


Testing the algorithm with an instance with more than one solution:

In [10]:
more_than_one_solution = np.array([[5, 3, 0, 0, 7, 0, 0, 0, 0],
                                   [6, 0, 0, 1, 9, 5, 0, 0, 0],
                                   [0, 9, 8, 0, 0, 0, 0, 6, 0],
                                   [8, 0, 0, 0, 6, 0, 0, 0, 3],
                                   [4, 0, 0, 8, 0, 3, 0, 0, 1],
                                   [7, 0, 0, 0, 2, 0, 0, 0, 6],
                                   [0, 6, 0, 0, 0, 0, 2, 8, 0],
                                   [0, 0, 0, 4, 1, 9, 0, 0, 5],
                                   [0, 0, 0, 0, 8, 0, 0, 0, 0]])

grid = exhaustive_search(more_than_one_solution)
print(grid)

None


Testing the algorithm with a no-solution instance:

In [11]:
no_solution = np.array([[5, 3, 0, 0, 7, 0, 1, 0, 0],
                        [6, 0, 0, 1, 9, 5, 0, 0, 0],
                        [0, 9, 8, 0, 0, 0, 0, 6, 0],
                        [8, 0, 0, 0, 6, 0, 0, 0, 3],
                        [4, 0, 0, 8, 0, 3, 0, 0, 1],
                        [7, 0, 0, 0, 2, 0, 0, 0, 6],
                        [0, 6, 0, 0, 0, 0, 2, 8, 0],
                        [0, 0, 0, 4, 1, 9, 0, 0, 5],
                        [0, 0, 0, 0, 8, 0, 0, 7, 9]])

grid = exhaustive_search(no_solution)
print(grid)

None
